#!/bin/sh
export LC_ALL=en
DaySuffix() {
  case `date +%d` in
      1|21|31) echo "st";;
      2|22)    echo "nd";;
      3|23)    echo "rd";;
      *)       echo "th";;
    esac
}

Month() {
    date +"%B"|sed -e "s/\b\(.\)/\u\1/g"
}
# 1st title (default=title with now + journal)
# 2nd date (default=now)
if [ "$#" -eq "0" ]; then
    title=$(date "+%d`DaySuffix` `Month` %Y")
    tag="Journal"
    date=$(date +"%F")
fi

if [ "$#" -eq "1" ]; then
    title=$1
    date=$(date +"%F")
    tag=""
fi

if [ "$#" -gt "1" ]; then
    title=$1
    date=$2
    tag=$3
fi


title_slug=$(echo $title|sed -e "s/ /-/g")
filename="$title_slug.md"
echo $filename

text="Title: $title
Date: $date
Tags: $tag
category: 
---"

if [ -f $filename ]; then
    read -p "$filename exists, do you want to override ?(y/n)" CONT
    if [ "$CONT" = "y" ]; then
        echo "$text" > $filename
    else
        exit 1
    fi
else
    echo "$text" > $filename
fi

echo "$text" > $filename
vim $filename
